In [1]:
import numpy as np
import pandas as pd

In [41]:
data = pd.read_csv('merged_data_correct.csv')

# (500-135)*228 = 83220
# 365 companies

### examine SIC codes

In [42]:
sic_list = sorted(data['SICCD'].unique().tolist())

In [43]:
print(len(sic_list))
print(sic_list)

201
['120', '1310', '1311', '1380', '1429', '1521', '1623', '1629', '180', '2013', '2046', '2070', '2080', '2090', '2110', '2190', '2270', '2282', '2310', '2329', '2330', '2339', '2510', '2522', '2541', '2640', '2672', '2710', '2711', '2810', '2819', '2821', '2830', '2834', '2836', '2840', '2844', '2850', '2890', '2910', '2911', '2992', '3010', '3079', '3081', '3089', '3140', '3171', '3210', '3241', '3291', '3296', '3310', '3360', '3399', '3420', '3440', '3460', '3465', '3490', '3499', '3510', '3520', '3523', '3533', '3540', '3550', '3560', '3570', '3577', '3585', '3610', '3629', '3660', '3661', '3663', '3670', '3672', '3674', '3679', '3690', '3692', '3710', '3714', '3715', '3720', '3743', '3810', '3811', '3820', '3826', '3840', '3845', '3860', '3861', '3910', '3970', '4190', '4200', '4210', '4212', '4730', '4812', '4813', '4832', '4833', '4890', '4910', '4911', '4920', '4924', '4930', '4941', '4950', '4953', '5000', '5010', '5012', '5032', '5040', '5050', '5060', '5064', '5080', '5086', '5090', '5099', '5111', '5120', '5122', '5130', '5140', '5311', '5330', '5411', '5510', '5511', '5531', '5640', '5712', '5730', '5810', '5812', '5900', '5910', '5940', '5960', '6020', '6021', '6022', '6025', '6030', '6090', '6099', '6141', '6150', '6210', '6211', '6282', '6311', '6330', '6331', '6361', '6513', '6531', '6710', '6711', '6712', '6719', '6798', '6799', '7011', '7260', '7350', '7353', '7370', '7372', '7373', '7379', '7380', '7389', '7391', '7539', '7820', '7929', '7940', '8060', '8062', '8071', '8090', '8220', '8299', '8322', '8730', '8731', '8740', '8741', '8742', '8780', '8980', 'Z']

**SIC 120 doesnt exist**

In [ ]:
# data.loc[data['SICCD'] == '120']

# one company: TEXAS INSTRUMENTS INC from 120 to 3674

**SIC 180 doesn't exist**

In [58]:
# data.loc[data['SICCD'] == '180']

# one company: GRIFFIN LAND AND NURSERIES INC to INDUS REALTY TRUST INC: 6500 real estate

,Unnamed: 0,Date,permno,return,mom1m,mom12m,chmom,indmom,mom36m,turn,...,beta,betasq,ep,sp,agr,nincr,return(t-1),r(t+1),SICCD,COMNAM
287,414,2001-01-31,85982,0.682784,-1.120278,0.031043,-0.270921,-0.094485,-0.407091,-0.902830,...,-1.122848,-0.817337,0.169297,-0.113205,0.101538,0.044234,NaN,0.741353,180,GRIFFIN LAND AND NURSERIES INC
652,914,2001-02-28,85982,0.733656,0.730101,-0.027564,-0.254182,0.014008,-0.466063,-0.902830,...,-1.243338,-0.848732,0.169297,-0.113205,0.101538,0.044234,0.683629,2.652268,180,GRIFFIN LAND AND NURSERIES INC
1017,1414,2001-03-31,85982,2.634073,0.383791,0.118082,-0.366926,0.271037,-0.546787,-0.897531,...,-1.222493,-0.843755,0.169297,-0.113205,0.101538,0.044234,0.734511,-0.231727,180,GRIFFIN LAND AND NURSERIES INC
1382,1914,2001-04-30,85982,-0.234078,2.785206,0.176672,0.629652,0.196406,-1.306698,-0.865465,...,-1.233181,-0.846331,0.169297,-0.113205,0.101538,-0.762600,2.635313,0.095708,180,GRIFFIN LAND AND NURSERIES INC
1747,2414,2001-05-31,85982,0.091558,-0.362564,0.695743,0.243841,0.181305,-0.620256,-0.853822,...,-1.216298,-0.842240,0.169297,-0.113205,0.101538,-0.762600,-0.233418,-0.693073,180,GRIFFIN LAND AND NURSERIES INC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81682,111914,2019-08-31,85982,-0.622563,0.678135,-0.534873,0.668149,-0.217860,-0.012560,-0.835939,...,-0.769544,-0.688653,0.035450,-0.519314,0.157593,-0.762600,0.667609,0.321769,180,GRIFFIN LAND AND NURSERIES INC
82047,112414,2019-09-30,85982,0.316377,-0.667732,-0.300158,0.391778,-0.287360,-0.049057,-0.816101,...,-0.727173,-0.669551,0.035450,-0.519314,0.157593,-0.762600,-0.621983,0.197853,180,GRIFFIN LAND AND NURSERIES INC
82412,112914,2019-10-31,85982,0.193142,0.329648,-0.390996,0.364791,-0.241948,-0.081468,-0.799156,...,-0.746227,-0.678238,0.035450,-0.519314,0.157593,-0.762600,0.317148,-0.223364,180,GRIFFIN LAND AND NURSERIES INC
82777,113414,2019-11-30,85982,-0.225761,0.199231,-0.081189,0.051187,0.072824,-0.196257,-0.668366,...,-0.656329,-0.635859,0.035450,-0.519314,0.157593,-0.762600,0.193888,0.163039,180,GRIFFIN LAND AND NURSERIES INC
83142,113914,2019-12-31,85982,0.158519,-0.237752,-0.049071,-0.015052,0.041124,-0.192631,-0.690234,...,-0.804455,-0.703800,0.035450,-0.519314,0.157593,-0.762600,-0.225100,NaN,180,GRIFFIN LAND AND NURSERIES INC

**SIC Z doesnt exist**

In [67]:
# print(1368/228) # 6 companies have Z as SIC
data.loc[data['SICCD'] == 'Z'].head(6)

,Unnamed: 0,Date,permno,return,mom1m,mom12m,chmom,indmom,mom36m,turn,...,beta,betasq,ep,sp,agr,nincr,return(t-1),r(t+1),SICCD,COMNAM
13,13,2001-01-31,16505,0.103253,0.302893,-0.417043,1.395487,-0.375241,-0.174171,-0.773837,...,-1.060043,-0.798454,0.238645,-0.359899,0.028813,0.044234,NaN,-0.036688,Z,BANCO DE PONCE P R
46,49,2001-01-31,20598,-1.191392,3.106962,0.141316,0.918749,0.336095,-0.810851,-0.699056,...,-0.589104,-0.601857,-1.071396,2.241951,0.072594,-0.762600,NaN,-0.632398,Z,CAL MAINE FOODS INC
71,76,2001-01-31,60186,-1.574244,2.023077,0.874790,-1.785257,-1.086263,-0.752070,-0.448126,...,-1.103006,-0.811558,0.311696,3.762771,-0.300605,0.044234,NaN,0.232266,Z,OWENS MINOR & BODEKER INC
72,77,2001-01-31,60206,0.321888,0.486967,-0.239535,0.084970,-0.719219,-0.750707,-0.454645,...,-0.826750,-0.713195,0.275118,-0.078845,-0.544727,0.851068,NaN,-0.341688,Z,SNAP ON TOOLS CORP
110,216,2001-01-31,79864,0.149224,-0.093663,-0.791766,-0.076121,-0.977841,-0.516501,-0.829223,...,-0.825424,-0.712642,0.305312,3.231824,1.063055,-0.762600,NaN,0.975828,Z,VALUE ENGR CO
363,496,2001-01-31,89317,1.178183,-3.109029,0.115178,-0.510151,-0.539431,-0.515650,-0.890677,...,-1.198277,-0.837735,0.790283,-0.291398,-2.366297,-0.762600,NaN,0.901753,Z,JOHNSTOWN CONSOLIDATED REALTY TR

In [ ]:
# BANCO DE PONCE P R - no record in EDGAR, but is a Pureto Rican bank, so 6082: Foreign Trade and International Banking Institutions
# CAL MAINE FOODS INC - 0200
# OWENS MINOR & BODEKER INC - no company with this name but OWENS MINOR exists w/ SIC 5047
# SNAP ON TOOLS CORP - 3420
# VALUE ENGR CO - no record in EDGAR, is VSE CORP, 8711 - Services-Engineering Services
# JOHNSTOWN CONSOLIDATED REALTY TR - no record in EDGAR, extremely old name, but should be TRANSCONTINENTAL REALTY INVESTORS INC right now: 6798

### quality control

In [78]:
data_clean = data.copy()

In [79]:
# TEXAS INSTRUMENTS INC from 120 to 3674
data_clean['SICCD'] = data_clean['SICCD'].apply(lambda x: '3674' if x == '120' else x)

In [80]:
# check
data_clean.loc[data_clean['COMNAM'] == 'TEXAS INSTRUMENTS INC']

,Unnamed: 0,Date,permno,return,mom1m,mom12m,chmom,indmom,mom36m,turn,...,beta,betasq,ep,sp,agr,nincr,return(t-1),r(t+1),SICCD,COMNAM
9,9,2001-01-31,15579,-0.514888,2.002559,-0.703399,-1.452016,-0.776086,3.261260,-0.121323,...,0.710106,0.443720,0.106827,-0.546381,-0.707507,5.692071,NaN,-2.849341,3674,TEXAS INSTRUMENTS INC
374,509,2001-02-28,15579,-2.837312,-0.676736,-0.496214,-0.680006,-1.186430,2.879692,-0.155411,...,0.694636,0.426925,0.106827,-0.546381,-0.707507,5.692071,-0.514286,0.464314,3674,TEXAS INSTRUMENTS INC
739,1009,2001-03-31,15579,0.458138,-2.622531,-1.179094,-0.722662,-1.316292,4.836932,-0.123450,...,0.487874,0.212503,0.106827,-0.546381,-0.707507,5.692071,-2.837179,1.837722,3674,TEXAS INSTRUMENTS INC
1104,1509,2001-04-30,15579,1.824002,0.282490,-1.485835,0.132649,-1.816217,5.038643,-0.054567,...,0.608193,0.335004,0.106827,-0.546381,-0.707507,-0.762600,0.458938,-0.931449,3674,TEXAS INSTRUMENTS INC
1469,2009,2001-05-31,15579,-0.929956,1.848633,-1.464588,0.370052,-1.828889,4.119250,-0.066408,...,0.496039,0.220616,0.106827,-0.546381,-0.707507,-0.762600,1.825077,-0.487185,3674,TEXAS INSTRUMENTS INC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81404,111509,2019-08-31,15579,-0.154108,0.652746,-0.157133,0.673291,-0.468869,0.376033,-0.313356,...,0.055642,-0.175308,0.224200,-0.523922,0.427132,-0.762600,0.583540,0.218625,3674,TEXAS INSTRUMENTS INC
81769,112009,2019-09-30,15579,0.213800,-0.172008,0.017798,0.455172,-0.487972,0.399317,-0.314750,...,0.067708,-0.165592,0.224200,-0.523922,0.427132,-0.762600,-0.153433,-0.681130,3674,TEXAS INSTRUMENTS INC
82134,112509,2019-10-31,15579,-0.681013,0.251174,0.100128,0.457022,-0.487608,0.299143,-0.332132,...,0.088096,-0.149028,0.224200,-0.523922,0.427132,-0.762600,0.214550,0.036265,3674,TEXAS INSTRUMENTS INC
82499,113009,2019-11-30,15579,0.032441,-0.716148,0.554147,-0.508168,-0.000870,0.061523,-0.315627,...,0.070077,-0.163676,0.224200,-0.523922,0.427132,-0.762600,-0.680443,0.374081,3674,TEXAS INSTRUMENTS INC
82864,113509,2019-12-31,15579,0.368402,0.052587,0.154994,0.213975,0.014624,0.097627,-0.343432,...,0.039143,-0.188492,0.224200,-0.523922,0.427132,-0.762600,0.033155,NaN,3674,TEXAS INSTRUMENTS INC

In [81]:
# INDUS REALTY TRUST INC
data_clean['SICCD'] = data_clean['SICCD'].apply(lambda x: '6500' if x == '180' else x)

In [82]:
# check
data_clean.loc[data_clean['COMNAM'] == 'GRIFFIN LAND AND NURSERIES INC']

,Unnamed: 0,Date,permno,return,mom1m,mom12m,chmom,indmom,mom36m,turn,...,beta,betasq,ep,sp,agr,nincr,return(t-1),r(t+1),SICCD,COMNAM
287,414,2001-01-31,85982,0.682784,-1.120278,0.031043,-0.270921,-0.094485,-0.407091,-0.902830,...,-1.122848,-0.817337,0.169297,-0.113205,0.101538,0.044234,NaN,0.741353,6500,GRIFFIN LAND AND NURSERIES INC
652,914,2001-02-28,85982,0.733656,0.730101,-0.027564,-0.254182,0.014008,-0.466063,-0.902830,...,-1.243338,-0.848732,0.169297,-0.113205,0.101538,0.044234,0.683629,2.652268,6500,GRIFFIN LAND AND NURSERIES INC
1017,1414,2001-03-31,85982,2.634073,0.383791,0.118082,-0.366926,0.271037,-0.546787,-0.897531,...,-1.222493,-0.843755,0.169297,-0.113205,0.101538,0.044234,0.734511,-0.231727,6500,GRIFFIN LAND AND NURSERIES INC
1382,1914,2001-04-30,85982,-0.234078,2.785206,0.176672,0.629652,0.196406,-1.306698,-0.865465,...,-1.233181,-0.846331,0.169297,-0.113205,0.101538,-0.762600,2.635313,0.095708,6500,GRIFFIN LAND AND NURSERIES INC
1747,2414,2001-05-31,85982,0.091558,-0.362564,0.695743,0.243841,0.181305,-0.620256,-0.853822,...,-1.216298,-0.842240,0.169297,-0.113205,0.101538,-0.762600,-0.233418,-0.693073,6500,GRIFFIN LAND AND NURSERIES INC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81682,111914,2019-08-31,85982,-0.622563,0.678135,-0.534873,0.668149,-0.217860,-0.012560,-0.835939,...,-0.769544,-0.688653,0.035450,-0.519314,0.157593,-0.762600,0.667609,0.321769,6500,GRIFFIN LAND AND NURSERIES INC
82047,112414,2019-09-30,85982,0.316377,-0.667732,-0.300158,0.391778,-0.287360,-0.049057,-0.816101,...,-0.727173,-0.669551,0.035450,-0.519314,0.157593,-0.762600,-0.621983,0.197853,6500,GRIFFIN LAND AND NURSERIES INC
82412,112914,2019-10-31,85982,0.193142,0.329648,-0.390996,0.364791,-0.241948,-0.081468,-0.799156,...,-0.746227,-0.678238,0.035450,-0.519314,0.157593,-0.762600,0.317148,-0.223364,6500,GRIFFIN LAND AND NURSERIES INC
82777,113414,2019-11-30,85982,-0.225761,0.199231,-0.081189,0.051187,0.072824,-0.196257,-0.668366,...,-0.656329,-0.635859,0.035450,-0.519314,0.157593,-0.762600,0.193888,0.163039,6500,GRIFFIN LAND AND NURSERIES INC
83142,113914,2019-12-31,85982,0.158519,-0.237752,-0.049071,-0.015052,0.041124,-0.192631,-0.690234,...,-0.804455,-0.703800,0.035450,-0.519314,0.157593,-0.762600,-0.225100,NaN,6500,GRIFFIN LAND AND NURSERIES INC

In [83]:
data_clean.loc[data_clean['COMNAM'] == 'BANCO DE PONCE P R', 'SICCD'] = '6082'
data_clean.loc[data_clean['COMNAM'] == 'CAL MAINE FOODS INC', 'SICCD'] = '0200'
data_clean.loc[data_clean['COMNAM'] == 'OWENS MINOR & BODEKER INC', 'SICCD'] = '5047'
data_clean.loc[data_clean['COMNAM'] == 'SNAP ON TOOLS CORP', 'SICCD'] = '3420'
data_clean.loc[data_clean['COMNAM'] == 'VALUE ENGR CO', 'SICCD'] = '8711'
data_clean.loc[data_clean['COMNAM'] == 'JOHNSTOWN CONSOLIDATED REALTY TR', 'SICCD'] = '6698'

In [56]:
# # check
# data_clean.loc[data_clean['COMNAM'] == 'BANCO DE PONCE P R']
# data_clean.loc[data_clean['COMNAM'] == 'CAL MAINE FOODS INC']
# data_clean.loc[data_clean['COMNAM'] == 'OWENS MINOR & BODEKER INC']
# data_clean.loc[data_clean['COMNAM'] == 'SNAP ON TOOLS CORP']
# data_clean.loc[data_clean['COMNAM'] == 'VALUE ENGR CO']
# data_clean.loc[data_clean['COMNAM'] == 'JOHNSTOWN CONSOLIDATED REALTY TR']

# all replaced

In [84]:
data_clean

,Unnamed: 0,Date,permno,return,mom1m,mom12m,chmom,indmom,mom36m,turn,...,beta,betasq,ep,sp,agr,nincr,return(t-1),r(t+1),SICCD,COMNAM
0,0,2001-01-31,13610,-1.577601,2.067047,-0.423509,1.027879,0.298817,-0.641896,-0.461379,...,-1.125798,-0.818182,0.109832,-0.005714,1.352752,3.271570,NaN,1.068007,2810,OLIN MATHIESON CHEM CORP
1,1,2001-01-31,13856,-0.928752,0.647658,0.318155,-0.292685,-0.154773,-0.359650,-0.551531,...,-1.604035,-0.904739,0.164941,-0.435813,1.039952,0.044234,NaN,0.234089,2090,PEPSI COLA CO
2,2,2001-01-31,13901,-0.034564,1.197333,1.209452,0.999410,1.010986,-0.840862,-0.486887,...,-1.633817,-0.906819,0.435438,-0.135575,0.262103,0.851068,NaN,0.580304,2110,PHILIP MORRIS INC
3,3,2001-01-31,13928,0.128928,-0.042072,0.194538,0.079124,1.010986,-0.332444,-0.465040,...,-1.516602,-0.896391,0.194226,-0.139399,0.122298,0.044234,NaN,-0.722710,2910,PHILLIPS PETROLEUM CO
4,4,2001-01-31,13936,-0.007235,-0.018197,0.849310,0.445356,-0.666015,-0.793118,-0.498117,...,-0.042420,-0.251914,0.300888,2.164993,0.340622,-0.762600,NaN,0.983025,2310,PHILLIPS VAN HEUSEN CORP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83215,113992,2019-12-31,88841,0.298062,0.405079,-0.474713,0.194469,-0.098352,-0.236953,-0.237796,...,0.177004,-0.074674,0.230596,0.006506,0.368983,-0.762600,0.347492,NaN,6022,RESOURCES CONNECTION INC
83216,113993,2019-12-31,88853,0.556482,0.548052,-1.416202,-0.108469,-0.802591,-0.591572,1.138001,...,1.588338,1.568930,0.191346,1.109432,0.476213,-0.762600,0.581698,NaN,1629,FLUOR CORP NEW
83217,113995,2019-12-31,89279,0.385862,0.079381,-0.722938,0.613486,-0.339810,-0.276255,-0.820610,...,-0.058042,-0.263729,0.146997,-0.516974,0.089618,0.044234,0.098223,NaN,6020,UNION BANKSHARES INC
83218,113996,2019-12-31,89317,0.990307,0.621034,-0.508996,0.971117,-0.534816,2.596698,-0.905457,...,0.968611,0.739869,0.984190,-0.371310,1.407156,-0.762600,0.566403,NaN,6698,JOHNSTOWN CONSOLIDATED REALTY TR
83219,113998,2019-12-31,89790,-0.065003,-0.756850,-0.065572,-0.229284,-1.688349,-0.114813,-0.430683,...,1.181609,1.005859,-0.138276,-0.592114,-1.143443,-0.762600,-0.703883,NaN,1311,MAGELLAN PETROLEUM CORP

In [85]:
sorted(data_clean['SICCD'].unique().tolist())

['0200',
 '1310',
 '1311',
 '1380',
 '1429',
 '1521',
 '1623',
 '1629',
 '2013',
 '2046',
 '2070',
 '2080',
 '2090',
 '2110',
 '2190',
 '2270',
 '2282',
 '2310',
 '2329',
 '2330',
 '2339',
 '2510',
 '2522',
 '2541',
 '2640',
 '2672',
 '2710',
 '2711',
 '2810',
 '2819',
 '2821',
 '2830',
 '2834',
 '2836',
 '2840',
 '2844',
 '2850',
 '2890',
 '2910',
 '2911',
 '2992',
 '3010',
 '3079',
 '3081',
 '3089',
 '3140',
 '3171',
 '3210',
 '3241',
 '3291',
 '3296',
 '3310',
 '3360',
 '3399',
 '3420',
 '3440',
 '3460',
 '3465',
 '3490',
 '3499',
 '3510',
 '3520',
 '3523',
 '3533',
 '3540',
 '3550',
 '3560',
 '3570',
 '3577',
 '3585',
 '3610',
 '3629',
 '3660',
 '3661',
 '3663',
 '3670',
 '3672',
 '3674',
 '3679',
 '3690',
 '3692',
 '3710',
 '3714',
 '3715',
 '3720',
 '3743',
 '3810',
 '3811',
 '3820',
 '3826',
 '3840',
 '3845',
 '3860',
 '3861',
 '3910',
 '3970',
 '4190',
 '4200',
 '4210',
 '4212',
 '4730',
 '4812',
 '4813',
 '4832',
 '4833',
 '4890',
 '4910',
 '4911',
 '4920',
 '4924',
 '4930',
 '4941',
 '4950',
 '4953',
 '5000',
 '5010',
 '5012',
 '5032',
 '5040',
 '5047',
 '5050',
 '5060',
 '5064',
 '5080',
 '5086',
 '5090',
 '5099',
 '5111',
 '5120',
 '5122',
 '5130',
 '5140',
 '5311',
 '5330',
 '5411',
 '5510',
 '5511',
 '5531',
 '5640',
 '5712',
 '5730',
 '5810',
 '5812',
 '5900',
 '5910',
 '5940',
 '5960',
 '6020',
 '6021',
 '6022',
 '6025',
 '6030',
 '6082',
 '6090',
 '6099',
 '6141',
 '6150',
 '6210',
 '6211',
 '6282',
 '6311',
 '6330',
 '6331',
 '6361',
 '6500',
 '6513',
 '6531',
 '6698',
 '6710',
 '6711',
 '6712',
 '6719',
 '6798',
 '6799',
 '7011',
 '7260',
 '7350',
 '7353',
 '7370',
 '7372',
 '7373',
 '7379',
 '7380',
 '7389',
 '7391',
 '7539',
 '7820',
 '7929',
 '7940',
 '8060',
 '8062',
 '8071',
 '8090',
 '8220',
 '8299',
 '8322',
 '8711',
 '8730',
 '8731',
 '8740',
 '8741',
 '8742',
 '8780',
 '8980']

In [86]:
data_clean.to_csv('less_messy_data_keyword_LESS.csv')

In [ ]:
# df = data.drop(columns = [ 'permno', 'return'])

In [1]:
# ### split data

# ##split training, validation, and testing datasets

# #training : validation : testing = 6 yr : 4yr : 9 yr <br>
# #Also drop the first and last month due to the absence of r(t+1) and return(t-1)

# training = df_scaled_2[:'2007-01-01'].dropna()
# validation = df_scaled_2['2007-01-01':'2011-01-01']
# testing = df_scaled_2['2011-01-01':].dropna()

# training_combined = df_scaled_2[:'2011-01-01'].dropna()


# ##separate X and y

# X_train = training.drop(columns = ['r(t+1)'])
# y_train = training['r(t+1)']

# X_val = validation.drop(columns = ['r(t+1)'])
# y_val = validation['r(t+1)']

# X_test = testing.drop(columns = ['r(t+1)'])
# y_test = testing['r(t+1)']

# X_train_combined = training_combined.drop(columns = ['r(t+1)'])
# y_train_combined = training_combined['r(t+1)']